version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  target-branch: dev
  ignore:
  - dependency-name: underscore
    versions:
    - 1.13.0
  - dependency-name: "@babel/core"
    versions:
    - 7.13.13
    - 7.13.15
  - dependency-name: mongoose
    versions:
    - 5.12.3
  - dependency-name: axios
    versions:
    - 0.21.1
  - dependency-name: debug
    versions:
    - 4.3.1
  - dependency-name: webpack-node-externals
    versions:
    - 2.5.2
  - dependency-name: webpack-cli
    versions:
    - 4.5.0
  - dependency-name: mocha
    versions:
    - 8.3.2
