language: node_js
node_js:
  - "lts/*"
before_script:
  - npm ci
jobs:
  include:
    - stage: "Test only"
      name: "Unit Test"
      script: npm test
    - stage: "Tests & Build"
      name: "Unit Tests and Build"
      script: npm run-script build

